<?php
$extensions = array();
//fields for fieldManager
$extensions[] = array(
	'module'=>'fieldManager',
	'type'=>'fields',
	'location'=>"file_field.fieldManager.extension",
	'data'=>array('fieldname'=>'file')
);
//fields for fieldManager
$extensions[] = array(
	'module'=>'fieldManager',
	'type'=>'fields',
	'location'=>"file_field.fieldManager.extension",
	'data'=>array('fieldname'=>'file')
);

//stream wrappers for fileManager
$extensions[] = array(
	'module'=>'fileManager',
	'type'=>'stream_wrappers',
	'location'=>"stream_wrappers/stream_wrapper_public.object",
	'data'=>array('scheme'=>'public')
);

$extensions[] = array(
	'module'=>'fileManager',
	'type'=>'stream_wrappers',
	'location'=>"stream_wrappers/stream_wrapper_tmp.object",
	'data'=>array('scheme'=>'tmp')
);

$objects = array();
$objects['fileManager'] = 'fileManager.object';
$objects['agaveStreamWrapper'] = 'stream_wrappers/agaveStreamWrapper.object';